// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjmwfudxxrhuhtckkmqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqbXdmdWR4eHJodWh0Y2trbXFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNjY4MTYsImV4cCI6MjA2Njc0MjgxNn0.NFjigrLc7T8uw5P11FT1vxfuRvbVw_LfWJUm_WivkXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);